// packages/react-ui/src/components/Container.tsx
import React from "react";
import { twMerge } from "tailwind-merge";

export interface ContainerProps extends React.HTMLAttributes<HTMLDivElement> {
  children?: React.ReactNode;
}

const Container = React.forwardRef<HTMLDivElement, ContainerProps>(
  ({ children, className, ...props }, ref) => {
    return (
      <div
      className={twMerge("mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 ", className)}
        ref={ref}
        {...props}
      >
        {children}
      </div>
    );
  }
);

Container.displayName = "Container";

export {Container};

// packages/vue/lib/Container/Container.vue
<script setup lang="ts">
import { twMerge } from "tailwind-merge";

const props = defineProps<{
  class?: string;
  children?: string;
}>();
</script>

<template>
  <div :class="twMerge('mx-auto max-w-7xl px-4 sm:px-6 lg:px-8', props.class)">
    <slot>
        {{ props.children }}
    </slot>
  </div>
</template>
