// packages/vue/lib/Breadcrumb/Breadcrumb.vue
<script setup lang="ts">
import { cva } from "class-variance-authority";
import { twMerge } from "tailwind-merge";
import Icon from "../Icon/Icon.vue";
import { computed } from "vue";

interface Page {
  name?: string;
  icon?: string;
  href: string;
  current: boolean;
}

const props = defineProps<{
  pages: Page[];
  size?: "sm" | "md" | "lg";
  icon?: string;
  class?: string;
}>();

const breadcrumbVariants = cva("flex items-center space-x-4", {
  variants: {
    size: {
      sm: "text-sm",
      md: "text-base",
      lg: "text-lg",
    },
  },
  defaultVariants: {
    size: "md",
  },
});

const breadcrumbClass = computed(() =>
  twMerge("flex items-center", props.class)
);
const listClass = computed(() => breadcrumbVariants({ size: props.size }));
</script>

<template>
  <nav :class="breadcrumbClass" aria-label="Breadcrumb">
    <ol role="list" :class="listClass">
      <li
        v-for="(page, index) in pages"
        :key="page.name || index"
        class="flex items-center"
      >
        <Icon
          v-if="index > 0"
          :name="icon || 'ChevronRight'"
          aria-hidden="true"
          class="h-5 w-5 shrink-0 text-secondary-400"
        />

        <slot name="link" :page="page">
          <a
            :href="page.href"
            :aria-current="page.current ? 'page' : undefined"
            class="ml-4 font-medium flex gap-2 items-center justify-center text-secondary-500 hover:text-secondary-700 dark:text-secondary-400 dark:hover:text-secondary-50"
          >
            <Icon
              v-if="page.icon"
              :name="page.icon"
              aria-hidden="true"
              variant="solid"
              class="size-5 shrink-0"
            />
            {{ page.name }}
          </a>
        </slot>
      </li>
    </ol>
  </nav>
</template>

// packages/react-ui/src/components/Breadcrumb.tsx
import React from "react";
import { Icon } from "./Icon";
import { cva, type VariantProps } from "class-variance-authority";
import { twMerge } from "tailwind-merge";

const breadcrumbVariants = cva("flex items-center space-x-4", {
  variants: {
    size: {
      sm: "text-sm",
      md: "text-base",
      lg: "text-lg",
    },
  },
  defaultVariants: {
    size: "md",
  },
});

type Page = {
  name?: string;
  icon?: string;
  href: string;
  current: boolean;
};

interface BreadcrumbLinkProps extends React.HTMLAttributes<HTMLAnchorElement> {
  page: Page;
  className?: string;
}

const BreadcrumbLink: React.FC<BreadcrumbLinkProps> = ({
  page,
  className,
  ...props
}) => (
  <a
    href={page.href}
    aria-current={page.current ? "page" : undefined}
    {...props}
    className={twMerge(
      "ml-4 font-medium flex gap-2 items-center justify-center text-secondary-500 hover:text-secondary-700 dark:text-secondary-400 dark:hover:text-secondary-50",
      className,
    )}
  >
    {page.icon && (
      <Icon
        name={page.icon}
        aria-hidden="true"
        variant="solid"
        className="size-5 shrink-0"
      />
    )}
    {page.name}
  </a>
);

interface BreadcrumbProps extends VariantProps<typeof breadcrumbVariants> {
  pages: Page[];
  icon?: string;
  className?: string;
  children?: (page: Page) => React.ReactNode;
}

BreadcrumbLink.displayName = "BreadcrumbLink";

const Breadcrumb: React.FC<BreadcrumbProps> & {
  Link: typeof BreadcrumbLink;
} = ({
  pages,
  size = "md",
  icon = "ChevronRight",
  className,
  children,
  ...props
}) => {
  return (
    <nav
      aria-label="Breadcrumb"
      className={twMerge("flex items-center", className)}
      {...props}
    >
      <ol role="list" className={twMerge(breadcrumbVariants({ size }))}>
        {pages.map((page, index) => (
          <li key={page.name || index} className="flex items-center">
            {index > 0 && (
              <Icon
                name={icon}
                aria-hidden="true"
                className="h-5 w-5 shrink-0 text-secondary-400"
              />
            )}
            {children ? <>{children(page)}</> : <BreadcrumbLink page={page} />}
          </li>
        ))}
      </ol>
    </nav>
  );
};

Breadcrumb.displayName = "Breadcrumb";
Breadcrumb.Link = BreadcrumbLink;

export { Breadcrumb, breadcrumbVariants };
