// packages/react-ui/lib/Textarea/Textarea.tsx
import React from "react";
import { twMerge } from "tailwind-merge";

interface TextareaProps extends React.HTMLAttributes<HTMLTextAreaElement> {
  rows?: number;
  label?: string;
  disabled?: boolean;
  placeholder?: string;
  id: string;
  name: string;
  value: string;
  onChange: (event: React.ChangeEvent<HTMLTextAreaElement>) => void;
}

const Textarea: React.FC<TextareaProps> = ({
  rows = 4,
  label,
  disabled = false,
  placeholder = "Add your comment...",
  id,
  name,
  value,
  className,
  onChange,
  ...props
}) => {
  return (
    <div>
      {label && (
        <label
          htmlFor={id}
          className="block text-sm/6 font-medium text-secondary-900 dark:text-secondary-100"
        >
          {label}
        </label>
      )}
      <div className="mt-2">
        <textarea
          id={id}
          name={name}
          rows={rows}
          disabled={disabled}
          placeholder={placeholder}
          value={value}
          onChange={onChange}
          className={twMerge(
            "block w-full rounded-md bg-white px-3 py-1.5 text-base text-secondary-900 outline-1 outline-secondary-300 disabled:bg-secondary-100 disabled:dark:bg-secondary-950 placeholder:text-secondary-400 dark:text-secondary-100 dark:bg-transparent dark:outline-secondary-600 dark:placeholder:text-secondary-500 focus:outline-2 focus:outline-primary-600 focus:-outline-offset-2 sm:text-sm/6 disabled:cursor-not-allowed",
            className,
          )}
          {...props}
        />
      </div>
    </div>
  );
};

export { Textarea };

// packages/vue/src/components/TextArea.vue
<script setup lang="ts">
import { cva } from "class-variance-authority";
import { twMerge } from "tailwind-merge";

const TextareaVariants = cva(
  "block w-full rounded-md bg-white px-3 py-1.5 text-base text-gray-900 outline-1 outline-gray-300 disabled:bg-gray-100 dark:text-gray-100 dark:bg-transparent dark:outline-gray-600 dark:placeholder-gray-500 focus:outline-2 focus:outline-primary-600 focus:-outline-offset-2 sm:text-sm disabled:cursor-not-allowed",
  {
    variants: {
      disabled: {
        true: "disabled:bg-secondary-100 disabled:dark:bg-secondary-950 cursor-not-allowed",
        false: "ocus:outline-2 focus:outline-primary-600 focus:-outline-offset-2",
      },
    },
    defaultVariants: {
      disabled: false,
    },
  },
);

const props = defineProps<{ 
  modelValue: string;
  rows?: number;
  label?: string;
  disabled?: boolean;
  placeholder?: string;
  id: string;
  name: string;
  class?: string;
}>();

defineEmits(["update:modelValue"]);

</script>


<template>
    <div>
      <label v-if="label" :for="id" class="block text-sm/6 font-medium text-secondary-900 dark:text-secondary-100">
        {{ label }}
      </label>
      <div class="mt-2">
        <textarea
          :id="id"
          :name="name"
          :rows="rows ?? 4"
          :disabled="disabled"
          :placeholder="placeholder"
          :value="modelValue"
          @input="$emit('update:modelValue', ($event.target as HTMLTextAreaElement).value)"
          :class="twMerge(TextareaVariants({ disabled }), props.class)"
        ></textarea>
      </div>
    </div>
  </template>
