// packages/vue/lib/Tabs/Tabs.vue
<template>
  <TabGroup>
    <div class="space-y-4">
      <TabList
        class="flex p-1.5 rounded-md bg-secondary-100 dark:bg-background-dark"
      >
        <Tab
          v-for="item in items"
          :key="item.label"
          as="template"
          v-slot="{ selected }"
        >
          <button
            :class="[
              'w-full py-2 text-sm leading-5 font-medium rounded-md transition-colors duration-100 cursor-pointer flex items-center justify-center gap-2',
              selected
                ? 'bg-primary-500 text-white dark:bg-primary-600'
                : 'text-secondary-700 dark:text-secondary-300',
            ]"
          >
            <Icon
              v-if="item.icon"
              :is="item.icon"
              :name="item.icon"
              :variant="iconVariant ?? 'outline'"
              class="w-4 h-4"
            />
            {{ item.label }}
          </button>
        </Tab>
      </TabList>

      <TabPanels>
        <TabPanel v-for="item in items" :key="item.label">
          <slot :name="item.slot" />
        </TabPanel>
      </TabPanels>
    </div>
  </TabGroup>
</template>

<script setup lang="ts">
import { TabGroup, TabList, Tab, TabPanels, TabPanel } from "@headlessui/vue";
import { defineProps } from "vue";
import Icon from "../Icon/Icon.vue";

interface TabItem {
  label: string;
  slot: string;
  icon?: string;
}

type IconVariant = "outline" | "solid";

defineProps<{
  items: TabItem[];
  iconVariant?: IconVariant;
}>();
</script>

// packages/react-ui/lib/Tabs/Tabs.tsx
import React from "react";
import { Tab, TabGroup, TabList, TabPanel } from "@headlessui/react";
import { twMerge } from "tailwind-merge";

interface TabsProps extends React.HTMLAttributes<HTMLDivElement> {
  children: React.ReactNode;
}

interface TabListProps extends React.HTMLAttributes<HTMLDivElement> {
  children: React.ReactNode;
}

interface TabsContentProps extends React.HTMLAttributes<HTMLDivElement> {
  children: React.ReactNode;
}

const Tabs = ({ className, children }: TabsProps) => {
  return (
    <TabGroup className={className}>
      <div className="space-y-4">{children}</div>
    </TabGroup>
  );
};

const TabsList: React.FC<TabListProps> = ({
  children,
  className,
  ...props
}) => {
  return (
    <TabList
      className={twMerge(
        "flex p-1.5 rounded-md bg-secondary-100 dark:bg-background-dark",
        className
      )}
      {...props}
    >
      {children}
    </TabList>
  );
};

const TabsContent: React.FC<TabsContentProps> = ({
  className,
  children,
}: TabsContentProps) => {
  return <TabPanel className={className}>{children}</TabPanel>;
};

interface TabsButtonProps
  extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  children?: React.ReactNode;
  className?: string;
}

const TabsButton: React.FC<TabsButtonProps> = ({
  className,
  children,
  ...props
}) => {
  return (
    <Tab
      className={twMerge(
        "w-full py-2 text-sm leading-5 font-medium rounded-md text-secondary-700 dark:text-secondary-300 transition-colors duration-100 cursor-pointer data-[selected]:bg-primary-500 data-[selected]:text-white dark:data-[selected]:bg-primary-600 ",
        className
      )}
      {...props}
    >
      {children}
    </Tab>
  );
};

Tabs.List = TabsList;
Tabs.Content = TabsContent;
Tabs.Button = TabsButton;

export { Tabs };
