// packages/vue/lib/RadioGroup/RadioGroup.vue
<script setup lang="ts">
import { twMerge } from "tailwind-merge";
import { cva } from "class-variance-authority";

const props = defineProps<{
  items: {
    id: string;
    label: string;
    description: string;
    value: string;
  }[];
  label?: string;
  description?: string;
  modelValue: string;
  class?: string;
}>();

const emit = defineEmits<{
  (e: "update:modelValue", value: string): void;
}>();

const handleChange = (value: string) => {
  emit("update:modelValue", value);
};

const baseInput = cva(
  "relative size-4 appearance-none rounded-full border border-secondary-300 bg-background-light before:absolute before:inset-1 before:rounded-full before:bg-background-light not-checked:before:hidden checked:border-indigo-600 checked:bg-indigo-600 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 disabled:border-secondary-300 disabled:bg-secondary-100 disabled:before:bg-secondary-400 dark:border-secondary-600 dark:bg-secondary-700 dark:checked:border-indigo-700 dark:checked:bg-indigo-700 dark:focus-visible:outline-indigo-400"
);
</script>

<template>
  <fieldset
    :aria-label="label"
    :class="twMerge(props.class, 'dark:text-gray-100 dark:border-secondary-600')"
  >
    <legend
      v-if="label"
      class="text-sm/6 font-semibold text-gray-900 dark:text-gray-100"
    >
      {{ label }}
    </legend>
    <p v-if="description" class="mt-1 text-sm/6 text-gray-600 dark:text-gray-400">
      {{ description }}
    </p>
    <div :class="twMerge('space-y-5', (label || description) ? 'mt-6' : '')">
      <div
        v-for="item in items"
        :key="item.id"
        class="relative flex items-start"
      >
        <div class="flex h-6 items-center">
          <input
            :id="item.id"
            :name="label"
            type="radio"
            :value="item.value"
            :checked="item.value === modelValue"
            @change="handleChange(item.value)"
            :aria-describedby="`${item.id}-description`"
            :class="twMerge(baseInput())"
          />
        </div>
        <div class="ml-3 text-sm/6">
          <label
            :for="item.id"
            class="font-medium text-secondary-900 dark:text-gray-100"
          >
            {{ item.label }}
          </label>
          <p
            :id="`${item.id}-description`"
            class="text-secondary-500 dark:text-secondary-400"
          >
            {{ item.description }}
          </p>
        </div>
      </div>
    </div>
  </fieldset>
</template>

// packages/react-ui/lib/RadioGroup/RadioGroup.tsx
import React from "react";
import { twMerge } from "tailwind-merge";

type Item = {
  id: string;
  label: string;
  description: string;
  value: string;
};

interface RadioGroupProps {
  items: Item[];
  label: string;
  description: string;
  value: string;
  onChange: (value: string) => void;
  className?: string;
}

const RadioGroup: React.FC<RadioGroupProps> = ({
  items,
  label,
  description,
  value,
  onChange,
  className,
  ...props
}) => {
  const handleChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    onChange(event.target.value);
  };

  return (
    <fieldset
      aria-label={label}
      className={twMerge(
        className,
        "dark:text-gray-100", // Text color in dark mode
        "dark:border-secondary-600" // Border color in dark mode
      )}
    >
      <legend className="text-sm/6 font-semibold text-gray-900 dark:text-gray-100">
        {label}
      </legend>
      <p className="mt-1 text-sm/6 text-gray-600 dark:text-gray-400">
        {description}
      </p>
      <div className={twMerge("space-y-5", label || description ? "mt-6" : "")}>
        {items.map((item) => (
          <div key={item.id} className="relative flex items-start">
            <div className="flex h-6 items-center">
              <input
                id={item.id}
                name={label}
                type="radio"
                aria-describedby={`${item.id}-description`}
                value={item.value}
                checked={item.value === value}
                onChange={handleChange}
                className={twMerge(
                  "relative size-4 appearance-none rounded-full border border-secondary-300 bg-background-light before:absolute before:inset-1 before:rounded-full before:bg-background-light not-checked:before:hidden checked:border-indigo-600 checked:bg-indigo-600 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 disabled:border-secondary-300 disabled:bg-secondary-100 disabled:before:bg-secondary-400 dark:border-secondary-600 dark:bg-secondary-700 dark:checked:border-indigo-700 dark:checked:bg-indigo-700 dark:focus-visible:outline-indigo-400"
                )}
                {...props}
              />
            </div>
            <div className="ml-3 text-sm/6">
              <label
                htmlFor={item.id}
                className="font-medium text-secondary-900 dark:text-gray-100"
              >
                {item.label}
              </label>
              <p
                id={`${item.id}-description`}
                className="text-secondary-500 dark:text-secondary-400"
              >
                {item.description}
              </p>
            </div>
          </div>
        ))}
      </div>
    </fieldset>
  );
};

export { RadioGroup };
